config/routes.rb
ArticleBrowser::Application.routes.draw do

  resources :articles do
    resources :comments
  end

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments


  attr_accessible :text, :title
  validates :text, :title, :presence => true


  def comments_ordered
    comments.order('created_at DESC')

  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :text, :article

  validates :text, :presence => true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new

    render 'new'

  end

  def index
    @articles = Article.all

  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments_ordered
    @comment = Comment.new

    if @article
      render 'show'
    else
      redirect_to root_path
    end
  end

  def create
    @article = Article.new(params[:article])

    if @article.save
      redirect_to root_path
    else
      render :action => "new"
    end

  end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new(:article => @article, :text => params[:comment][:text])
    respond_to do |format|
      if @comment.save
        format.html {render @article}
        format.js
      else
        format.html {render @article}
        format.js {render :alert => @comment.errors, :status  => :unprocessable_entity}
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article_list.html.erb
<h3> <%= link_to article_list.title, article_path(article_list.id) %>  </h3>
<ul class="style2">
  <%= truncate article_list.text, :length => 50, :omission => '... (continued)'%>
</ul>

app/views/articles/_form.html.erb
<%= simple_form_for @article, :url => articles_path, :method => 'POST' do |f| %>

    <%= f.input :title %>
    <%= f.input :text, :input_html =>{ :style => 'width: 580px'} %>

    <%= f.submit 'create', :class => 'button' %>


<% end %>

app/views/articles/index.html.erb
<div id="page" class="container" xmlns="http://www.w3.org/1999/html">
  <div id="content2">
    <div class="title centered">
      <h1>List of all articles</h1>
      <%= link_to 'Add article', new_article_path, :class => "icon icon-arrow-right button" %>

    </div>

    <%= render :partial => "article_list", :collection => @articles %>

  </div>
</div>

app/views/articles/new.html.erb
<div id="page" class="container" xmlns="http://www.w3.org/1999/html">
  <div id="content2">
    <div class="title centered">
      <h1>Create an article</h1>
    </div>

    <%= render 'form' %>


  </div>
</div>

app/views/articles/show.html.erb
<div id="page" class="container" xmlns="http://www.w3.org/1999/html">
  <div id="content2">
    <div class="title centered">
      <h1><%= @article.title %></h1>
    </div>

    <ul class="style2">
      <%= simple_format @article.text %>
    </ul>


    <h2>Comments</h2>

    <div id="comments">
      <%= render :partial => "comments/comment", :collection => @comments %>
    </div>

    <%= render 'comments/form' %>


  </div>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
  <h3 class="time_ago"><%= comment.created_at %></h3>
  <em><%= simple_format comment.text %></em>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for @comment, :url => article_comments_path(@article.id), :method => 'POST', :remote => true do |f| %>
    <h2>Add comment</h2>

    <%= f.input :text %>
    <%= f.submit 'Add comment', :class => 'button' %>



<% end %>

app/views/comments/create.js.erb
c = "<div class='comment'><h3 class='time_ago'><%= @comment.created_at %> </h3><em> <%= escape_javascript(simple_format  @comment.text) %></em></div>"


$('#comments').prepend(c);
document.getElementById('comments').scrollIntoView(true);

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articlator</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
  <div id="menu-wrapper">
    <div id="menu" class="container">
      <ul>
        <li class="<%= "current_page_item" if current_page?(root_path) %>"><%= link_to "All articles", root_path %></li>
      </ul>
    </div>
    <!-- end #menu -->
  </div>
  <div id="header-wrapper">
    <div id="header" class="container">
      <div id="logo">
        <h1><a href="/">Articlator</a></h1>

        <p>Add and comment all types of arcticles</p>
      </div>
    </div>
  </div>

  <%= render 'layouts/messages' %>


  <%= yield %>

</div>

<div id="copyright" class="container">
  <p>Copyright (c) 2014 Lubomir Vnenk | Design by
    <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>. | Give
    feedback at lubomir.vnenk@zoho.com </p>
</div>

</body>
</html>